services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_DB: wageanalysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - postgres_default  
volumes:
  db:
    driver: local

networks:
  postgres_default:
    external: true